version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: 'library'
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: '1234'


